project:
  type: website

website:
  title: "Wyara Silva"
  navbar:
    right:
      - about.qmd
      - icon: github
        text: GitHub
        href: https://github.com/wyaravms
      - icon: twitter
        text: Twitter
        href: https://twitter.com/wyaravms
format:
  html:
    theme: darkly
    css: styles.css

editor: visual

comments:
  giscus:
    repo: wyaravms/personal-blog
